# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-13 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leonardo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('nombre_completo', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('numero_celular', models.IntegerField()),
            ],
        ),
    ]
